---
title: "Calculadora de Malles"
author: "Miquel Murillo Saez"
date: "`r Sys.Date()`"
output: html_document
---
## Notes Antic
CTC1S1, 0.9, 20.1
CTC1S2, 0.9, 5.1
CTC1S3, 0.9, 13.1
CTC2S1, 0.9, 10.1
CTC2S2, 0.9, 8.1
CTC2S3, 0.9, 11.1
CTC3S1, 0.9, 3.1
CTC4S1, 0.9, 2.1
CTC5S1, 0.9, 4.1
CTC6S1, 0.9, 10.1
CTC7S1, 0.9, 4.1
CTC8S1 No és necessàri, només R7A

## Notes Simplificat

Vic - La Tor TVU1, 0.9, 11.1

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
library(openxlsx)
source("fc.R")
```

```{r data_objects}
CTC1S1 <- read_xlsx(here("dades","1S1.xlsx"))
CTC1S1_h <- read_xlsx(here("dades","1S1.xlsx"))|>
  mutate( departure = format(departure, "%H:%M"))
CTC1S2 <- read_xlsx(here("dades","1S2.xlsx"))
CTC1S2_h <- read_xlsx(here("dades","1S2.xlsx"))|>
  mutate( departure = format(departure, "%H:%M"))
CTC1S3 <- read_xlsx(here("dades","1S3.xlsx"))
CTC1S3_h <- read_xlsx(here("dades","1S3.xlsx"))|>
  mutate( departure = format(departure, "%H:%M"))
CTC2S1 <- read_xlsx(here("dades","2S1.xlsx"))
CTC2S1_h <- read_xlsx(here("dades","2S1.xlsx"))|>
  mutate( departure = format(departure, "%H:%M"))
CTC2S2 <- read_xlsx(here("dades","2S2.xlsx"))
CTC2S2_h <- read_xlsx(here("dades","2S2.xlsx"))|>
  mutate( departure = format(departure, "%H:%M"))
CTC2S3 <- read_xlsx(here("dades","2S3.xlsx"))
CTC2S3_h <- read_xlsx(here("dades","2S3.xlsx"))|>
  mutate( departure = format(departure, "%H:%M"))
CTC3S1 <- read_xlsx(here("dades","3S1.xlsx"))
CTC3S1_h <- read_xlsx(here("dades","3S1.xlsx"))|>
  mutate( departure = format(departure, "%H:%M"))
CTC4S1 <- read_xlsx(here("dades","4S1.xlsx"))
CTC4S1_h <- read_xlsx(here("dades","4S1.xlsx"))|>
  mutate( departure = format(departure, "%H:%M"))
CTC5S1 <- read_xlsx(here("dades","5S1.xlsx"))
CTC5S1_h <- read_xlsx(here("dades","5S1.xlsx"))|>
  mutate( departure = format(departure, "%H:%M"))
CTC6S1 <- read_xlsx(here("dades","6S1.xlsx"))
CTC6S1_h <- read_xlsx(here("dades","6S1.xlsx"))|>
  mutate( departure = format(departure, "%H:%M"))
CTC7S1 <- read_xlsx(here("dades","7S1.xlsx"))
CTC7S1_h <- read_xlsx(here("dades","7S1.xlsx"))|>
  mutate( departure = format(departure, "%H:%M"))

## Dades Simplificat

TVU1 <- read_xlsx(here("dades","TVU1.xlsx"))
TVU1_h <- read_xlsx(here("dades","TVU1.xlsx"))|>
  mutate( departure = format(departure, "%H:%M"))
```

```{r generador_malla}
malla_TVU1 <- GetMalla(TVU1, 0.9, 11.1)
ExportMalla(malla_TVU1, "TVU1.jpg")
## Per tenir bé l'eix x cal posar tots els punts en ordre al principi sense dades
```

```{r generador_horaris_estacions}
Badalona_central_horari <- CTC1S1 %>%
  filter(station == "Badalona Central") %>%
  arrange(departure)
## Cal fer servir l'objecte amb _h per eliminar el 1899
```

```{r generador_horaris_trens}
R1A_001_horari <- CTC1S1_h %>%
  filter(train_number == "R1A.001") %>%
  arrange(departure)
## Cal fer servir l'objecte amb _h per eliminar el 1899
```

```{r generador_horaris_estacions_un_sentit}
Malgrat_de_mar_horari_macanet <- CTC1S1 %>%
  filter(station == "MALGRAT DE MAR") %>%
   filter(destination == "Maçanet-Massanes") %>%
  arrange(departure)
## Cal fer servir l'objecte amb _h per eliminar el 1899
```

```{r generador_excels}
write.xlsx(Malgrat_de_mar_horari,here("horaris_generats","Malgrat_de_mar_horari.xlsx"),colNames = TRUE)
## Cal canviar l'objecte i el nom del document cada nou horari
```
